---
title: "Airbnb Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, include = FALSE}
data("nyc_airbnb")

nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type, lat, long, rating) %>% 
  filter(!is.na(rating), 
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, 
    type = "scatter", mode = "markers", 
    alpha = 0.5, text = ~text_label
  )
```

### Chart C

```{r}

```

