---
title: "NYC Restaurant Inspection Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r, include=FALSE}
data("rest_inspec")

rest_df = rest_inspec %>% 
  sample_n(2000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Insecption Score by Date of Inspection  

```{r}
rest_df %>% 
    plot_ly(
    x = ~inspection_date, y = ~score, color = ~boro, 
    type = "scatter", mode = "markers", colors = "viridis", 
    alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Restaurants by Borough

```{r}
rest_df %>%  
 count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
```

### Distribution of Insepction Scores by Borough

```{r}
rest_df %>% 
  mutate(boro = fct_reorder(boro, score)) %>%  
      plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")

```

