---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We're going to make some plotly plots. 

## Load packages and data 

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Lets get data. 

```{r}
data("nyc_airbnb")

nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type, lat, long, rating) %>% 
  filter(!is.na(rating), 
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Lets make a scatterplot!!

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, 
    type = "scatter", mode = "markers", 
    alpha = 0.5, text = ~text_label
  )
```


can we make boxplots 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
    plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

can we make a bar plot 

```{r}
##first you need to define the number of observations in each to make the height of the bar

nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

##ggplotly.. MUCH CH

```{r}
ggp_catterplot = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point(alpha = 0.25)

ggplotly(ggp_catterplot)
```


